# Cargo configuration for foiacquire
# https://doc.rust-lang.org/cargo/reference/config.html

[alias]
faq = "run --release --features postgres,browser --"
serve = "run --release --features postgres -- serve"
scrape = "run --release --features postgres,browser -- scrape"
ocr = "run --release --features postgres -- ocr"
status = "run --release --features postgres -- status"
